CPPFLAGS= -Wall -g -std=c++11 -lboost_filesystem -lboost_system

all:
	make -j4 sum
	make -j4 hello_world
	make -j4 mult
	make -j4 sum_of_x
	make -j4 print_to_zero
	make -j4 print_range
	make -j4 sum_dynamic
	make -j4 matches
	make -j4 factorial
	make -j4 calculator
	make -j4 temp_convert_and_step
	make -j4 walker

clean:
	rm -f sum
	rm -f hello_world
	rm -f mult
	rm -f sum_of_x
	rm -f print_to_zero
	rm -f print_range
	rm -f sum_dynamic
	rm -f matches
	rm -f factorial
	rm -f calculator
	rm -f temp_convert_and_step
	rm -f walker
