CPPFLAGS= -Wall -g

all:
	make -j4 sum
	make -j4 hello_world
	make -j4 mult
	make -j4 sum_of_x
	make -j4 print_to_zero
	make -j4 print_range

clean:
	rm -f sum
	rm -f hello_world
	rm -f mult
	rm -f sum_of_x
	rm -f print_to_zero
	rm -f print_range
