CFLAGS=-Wall -g

all:
	make -j4 ex1
	make -j4 ex2
	make -j4 ex3
	make -j4 ex4
	make -j4 ex5
	make -j4 ex6
	make -j4 ex7
clean:
	rm -f ex1
	rm -f ex2
	rm -f ex3
	rm -f ex4
	rm -f ex5
	rm -f ex6
	rm -f ex7
