CPPFLAGS= -Wall -g -std=c++11

all:
	make -j4 multiples_of_3_and_5
	make -j4 even_fibonacci_numbers
	make -j4 largest_prime_factor
	make -j4 largest_palindrome
	make -j4 smallest_multiple

clean:
	rm -f multiples_of_3_and_5
	rm -f even_fibonacci_numbers
	rm -f largest_prime_factor
	rm -f largest_palindrome
	rm -f smallest_multiple
