CC = g++
CFLAGS = -Wall -g -std=c++11

1-multiples_of_3_and_5:
	${CC} ${CFLAGS} 1-multiples_of_3_and_5.cpp -o 1-multiples_of_3_and_5

2-even_fibonacci_numbers:
	${CC} ${CFLAGS} 2-even_fibonacci_numbers.cpp -o 2-even_fibonacci_numbers

3-largest_prime_factor:
	${CC} ${CFLAGS} 3-largest_prime_factor.cpp -o 3-largest_prime_factor

4-largest_palindrome:
	${CC} ${CFLAGS} 4-largest_palindrome.cpp -o 4-largest_palindrome

5-smallest_multiple:
	${CC} ${CFLAGS} 5-smallest_multiple.cpp -o 5-smallest_multiple

6-sum_square_difference:
	${CC} ${CFLAGS} 6-sum_square_difference.cpp -o 6-sum_square_difference

7-10001st_prime:
	${CC} ${CFLAGS} 7-10001st_prime.cpp -o 7-10001st_prime

8-largest_product_in_series:
	${CC} ${CFLAGS} 8-largest_product_in_series.cpp -o 8-largest_product_in_series

9-special_pythagorean_triplet:
	${CC} ${CFLAGS} 9-special_pythagorean_triplet.cpp -o 9-special_pythagorean_triplet

10-summation_of_primes:
	${CC} ${CFLAGS} 10-summation_of_primes.cpp -o 10-summation_of_primes

profile:
	${CC} ${CFLAGS} 10-summation_of_primes.cpp -o 10-summation_of_primes -pg

 all:
	make 1-multiples_of_3_and_5
	make 2-even_fibonacci_numbers
	make 3-largest_prime_factor
	make 4-largest_palindrome
	make 5-smallest_multiple
	make 6-sum_square_difference
	make 7-10001st_prime
	make 8-largest_product_in_series
	make 9-special_pythagorean_triplet
	make 10-summation_of_primes

 clean:
	rm -f 1-multiples_of_3_and_5
	rm -f 2-even_fibonacci_numbers
	rm -f 3-largest_prime_factor
	rm -f 4-largest_palindrome
	rm -f 5-smallest_multiple
	rm -f 6-sum_square_difference
	rm -f 7-10001st_prime
	rm -f 8-largest_product_in_series
	rm -f 9-special_pythagorean_triplet
	rm -f 10-summation_of_primes
