CPPFLAGS= -Wall -g -std=c++11

all:
	make -j4 1-multiples_of_3_and_5
	make -j4 2-even_fibonacci_numbers
	make -j4 3-largest_prime_factor
	make -j4 4-largest_palindrome
	make -j4 5-smallest_multiple
	make -j4 6-sum_square_difference
	make -j4 7-10001st_prime
	make -j4 8-largest_product_in_series

clean:
	rm -f 1-multiples_of_3_and_5
	rm -f 2-even_fibonacci_numbers
	rm -f 3-largest_prime_factor
	rm -f 4-largest_palindrome
	rm -f 5-smallest_multiple
	rm -f 6-sum_square_difference
	rm -f 7-10001st_prime
	rm -f 8-largest_product_in_series
