######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 16 18:31:53 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += hasher.h
SOURCES += hasher.cpp main.cpp
