######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 17 20:15:25 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lcrypto
QMAKE_CXXFLAGS += -std=c++11

# Input
HEADERS += hasher.h
SOURCES += hasher.cpp main.cpp
